export type PolicyOutcome = 'allow' | 'deny' | 'require_approval';

export const POLICY_REASON = {
  AUTHORITY_APPROVAL_REQUIRED: 'AUTHORITY_APPROVAL_REQUIRED',
  PRODUCT_MATERIAL_FORBIDDEN: 'PRODUCT_MATERIAL_FORBIDDEN',
  OUT_OF_STOCK: 'OUT_OF_STOCK',
  HARD_CAP_EXCEEDED: 'HARD_CAP_EXCEEDED',
} as const;
